FROM {{ hailgenetics/genetics:0.2.37 }}

RUN mkdir htslib && \
	(cd htslib && \
    curl -LO https://github.com/samtools/htslib/releases/download/1.10.2/htslib-1.10.2.tar.bz2 && \
    tar -xf htslib-1.10.2.tar.bz2 && \
    rm -rf htslib-1.10.2.tar.bz2 && \
    cd htslib-1.10.2 && \
    ./configure --prefix=$PWD && \
    make && \
    make install &&
	mv tabix bgzip /bin/ )